### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by UnderseaKnight** [chris124567/hulu#13]
I have no idea how to get this started, struggling to download bento4 and YT-DLP or whatever those two things are, and I'm also struggling to understand the rest of the guide as well. A video would be nice to show how to install all of these (Except bento4 and YT-DLP, since those are libraries not made or owned by you).

**Comment by UnderseaKnight** [comment]
Im figuring out Bento4 and YT DLP, but still need help with this.

**Comment by UnderseaKnight** [comment]
Figured out Bento4, still need help with YT-DLP

**Comment by michael-hart-github** [comment]
@UnderseaKnight If you are still struggling, hopefully I can at least give a bit of context for you:

`yt-dlp` is a fork of an application called `youtube-dl`. The initial intention of `youtube-dl` was to help people download (dl) videos from YouTube. From what I have gathered, `youtube-dl` fell out of favor due to lack of updates, and slow download speeds. `yt-dlp` took its place.

You can find a very, _very_ detailed guide of `yt-dlp` [here](https://github.com/yt-dlp/yt-dlp). `yt-dlp` has support for [a LOT of different websites](https://docs.yt-dlp.org/en/latest/supportedsites.html). It's generally a very nice resource to have. It can just get fairly complicated if you're trying to do something very specific or fancy. It seems like this repo, `hulu` is trying to do something fancy.

I've read through the readme for this repo and, honestly, find it a bit confusing, too. From the description, it sounds like you need to download the audio and video differently, then combine them together. This isn't the norm for how I've used `yt-dlp` in the past, so I'm a bit out of my depth at the moment.

Maybe if you practice downloading some youtube videos first with `yt-dlp`, you can get a bit more comfortable with using the program?

**Comment by UnderseaKnight** [comment]
Maybe, Ill try that i think.

**Comment by chris124567** [comment]
Apologies for the late reply.  The above comment about yt-dlp should help you.  This software doesn't actually work by default anymore unless you have your own Widevine private key.  Widevine has been revoking all the leaked keys lately which is why I stopped updating the repository.  If you can find your own key then it should work (you would need to update `widevine/consts.go`).

**Comment by michael-hart-github** [comment]
@chris124567 Thanks for the info and response. Based on what I had seen in the readme, it did sound like there was some weirdness with Widevine. Thank you for clarifying. :+1: 

It's a shame that there's such a push to restrict customers from being able to access content that they pay for in a medium other than a monthly bill ad infinitum - with literally no recourse for the customers - should the provider decide to remove it for any reason whatever.

It concerns me that future generations chances of being able to view content in the same manner that we have been able to for **generations** at this point will be very few and far between when it comes to "(streaming platform) exclusive" content. Servers shut down. Hard drives die. It's sad to think how much of that will never be accessible again by the general public in as little as even 10 to 20 years from now. :frowning_face:

**Comment by chris124567** [comment]
@michael-hart-github It is indeed very frustrating.  The existence of torrent sites proves they're losing and I suspect they will continue to because even if they had DRM down perfectly nothing is stopping people from aiming a camera at their screen.
